"""update label structure

Revision ID: 140305975d0d
Revises: d28f2b2eef30
Create Date: 2023-06-22 14:49:28.919894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "140305975d0d"
down_revision = "d28f2b2eef30"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("labels", sa.Column("color", sa.String(), nullable=False))
    op.add_column(
        "labels", sa.Column("description", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("labels", "description")
    op.drop_column("labels", "color")
    # ### end Alembic commands ###
