"""add labels table

Revision ID: d28f2b2eef30
Revises: 0336949bd11f
Create Date: 2023-06-12 19:13:24.935845

"""
from alembic import op
import sqlalchemy as sa
import app.utils.guid


# revision identifiers, used by Alembic.
revision = "d28f2b2eef30"
down_revision = "0336949bd11f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "labels",
        sa.Column("id", app.utils.guid.GUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("dataset_id", app.utils.guid.GUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["dataset_id"],
            ["datasets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("dataset_id", "name"),
    )
    op.create_index(op.f("ix_labels_id"), "labels", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_labels_id"), table_name="labels")
    op.drop_table("labels")
    # ### end Alembic commands ###
